apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-app.fullname" . }}
type: Opaque
stringData:
  username: {{ .Values.secretData.username | quote }}
  password: {{ .Values.secretData.password | quote }}
