replicaCount: 2

image:
  repository: nginx
  tag: "1.25"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

configData:
  welcome: "Hello from ConfigMap!"

secretData:
  username: "admin"
  password: "password"
